# Generated by Django 5.1.3 on 2025-06-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=50)),
                ('cuisine', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('tags', models.JSONField()),
            ],
        ),
    ]
