# Generated by Django 5.1.3 on 2025-07-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
    ]
