# Generated by Django 5.1.3 on 2025-07-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_price_hotel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(default='https://your-project-id.supabase.co/storage/v1/object/public/media/placeholder.jpg'),
            preserve_default=False,
        ),
    ]
