# Generated by Django 5.1.3 on 2025-07-03 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('model', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=50)),
                ('total_seats', models.PositiveIntegerField()),
                ('economy_seats', models.PositiveIntegerField()),
                ('business_seats', models.PositiveIntegerField(default=0)),
                ('first_class_seats', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('duration', models.CharField(max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('baggage_allowance', models.CharField(max_length=50)),
                ('meal_included', models.BooleanField(default=False)),
                ('wifi_available', models.BooleanField(default=False)),
                ('entertainment_available', models.BooleanField(default=False)),
                ('power_outlet_available', models.BooleanField(default=False)),
                ('booking_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('cancellation_policy', models.TextField()),
                ('refund_policy', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('arrived', 'Arrived')], default='scheduled', max_length=20)),
                ('gate', models.CharField(blank=True, max_length=10, null=True)),
                ('terminal', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airline')),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport')),
            ],
            options={
                'ordering': ['departure_datetime'],
            },
        ),
        migrations.CreateModel(
            name='FlightSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('booking_class', models.CharField(default='economy', max_length=20)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], max_length=20)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_departures', to='flights.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_arrivals', to='flights.airport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('book', 'Book')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.flightsearch')),
            ],
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['from_airport', 'to_airport', 'departure_datetime'], name='flights_fli_from_ai_642bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_datetime'], name='flights_fli_departu_f18c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['status'], name='flights_fli_status_e6e528_idx'),
        ),
        migrations.AddIndex(
            model_name='flightanalytics',
            index=models.Index(fields=['flight', 'action', 'timestamp'], name='flights_fli_flight__d1bb54_idx'),
        ),
    ]
