# Generated by Django 5.1.3 on 2025-06-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_create_admin_user'),
        ('authentication', '0002_userprofile_delete_featuredestination_and_more'),
    ]

    operations = [
    ]
