# Generated by Django 5.1.3 on 2025-07-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_featuredestination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='destination_images/')),
                ('description', models.TextField()),
                ('click', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
