# Generated by Django 5.1.3 on 2025-07-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.RemoveField(
            model_name='featuredestination',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='background_image',
        ),
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(default='https://your-project-id.supabase.co/storage/v1/object/public/media/placeholder.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuredestination',
            name='image_url',
            field=models.URLField(default='https://your-project-id.supabase.co/storage/v1/object/public/media/placeholder.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosection',
            name='image_url',
            field=models.URLField(default='https://your-project-id.supabase.co/storage/v1/object/public/media/placeholder.jpg'),
            preserve_default=False,
        ),
    ]
