# Generated by Django 5.1.3 on 2025-07-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_destination_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='large_description',
            field=models.TextField(default='description here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuredestination',
            name='large_description',
            field=models.TextField(default='description here'),
            preserve_default=False,
        ),
    ]
