# Generated by Django 5.1.3 on 2025-07-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_destination_large_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=100)),
                ('bestTime', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('heroImage', models.URLField()),
            ],
        ),
    ]
